en:
    links.all-posts: "All Posts"
    links.read-more: "Read More..."
    headings.latest-posts: "Latest Posts"
    headings.featured-posts: "Featured Posts"
    headings.search-results: "Search Results"
    general.paginated-posts-list: "This is a paginated list of posts"
    general.posted-in: "Posted in"
    general.related-posts: "Related Posts"
    general.posts-tagged: "Posts Tagged"
    posts.user.posts-by: "Posts By"
    posts.user.read-all-posts-by: "Read all of the posts by"
    search.you-searched-for: "You searched for"
    search.all-posts-from: "All posts from"
    search.matching-the-query: "matching the query"
    search.search-results-for: "Search results for"
    search.search-for-posts: "Search for posts"
    page.404.title: "Page Not Found"
    page.404.message: "We're sorry, but the page you requested cannot be found."
    page.500.title: "Error"
    page.500.message: "We're sorry, but something went wrong and the page cannot be displayed."
    footer.useful-links: "Useful Links"
    footer.this-theme: "This Theme"
    footer.the-author: "The Author"
    footer.rss-feed: "RSS Feed"
    footer.sitemap: "Sitemap"
    footer.credits: "Credits"
    footer.on-github: "On Github"
    footer.at-twitter: "At Twitter"
    footer.at-linkedin: "At LinkedIn"
    category.list-subcategories: "Read more in"

de:
    links.all-posts: "Alle Beiträge"
    links.read-more: "Weiterlesen..."
    headings.latest-posts: "Neueste Beiträge"
    headings.featured-posts: "Beliebte Beiträge"
    headings.search-results: "Suchergebnisse"
    search.you-searched-for: "Sie suchten nach"
    search.all-posts-from: "Alle Beiträge von"
    search.matching-the-query: "passend zur Suchanfrage"
    search.search-results-for: "Suchergebnisse für"
    search.search-for-posts: "Nach Beiträgen suchen"
    general.paginated-posts-list: "Dies ist eine paginierte Liste von Beiträgen"
    general.posted-in: "Veröffentlicht in"
    general.related-posts: "zusammenhängende Posts"
    general.posts-tagged: "Getaggte Beiträge"
    posts.user.posts-by: "Beiträge von"
    posts.user.read-all-posts-by: "Lesen Sie alle Beiträge von"
    page.404.title: "Seite nicht gefunden"
    page.404.message: "Es tut uns leid, aber die von Ihnen angeforderte Seite kann nicht gefunden werden."
    page.500.title: "Fehler"
    page.500.message: "Es tut uns leid, aber ein Fehler ist aufgetreten und die Seite kann nicht angezeigt werden."
    footer.useful-links: "Nützliche Links"
    footer.this-theme: "Dieses Thema"
    footer.the-author: "Der Autor"
    footer.rss-feed: "RSS-Feed"
    footer.sitemap: "Seitenverzeichnis"
    footer.credits: "Credits"
    footer.on-github: "Auf Github"
    footer.at-twitter: "Bei Twitter"
    footer.at-linkedin: "Bei LinkedIn"
    category.list-subcategories: "Lesen Sie mehr in"

